name: Compilation check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  compile_examples:
    name: Compile examples
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Update
      run: |
        apt-get update -y
        apt-get upgrade -y
        apt-get install doxygen -y

    - name: Build tinyalsa
      run: |
        mkdir -p /usr/local/include/
        cd /home/runner/work/
        git clone https://github.com/tinyalsa/tinyalsa.git
        cd tinyalsa
        make
        make install
        ldconfig

    - name: Build tinycap
      run: go build example/tinycap.go
